 updateClock(){const n=new Date();document.getElementById('liveClock').textContent=n.toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit',second:'2-digit'});document.getElementById('liveDate').textContent=n.toLocaleDateString('fa-IR',{weekday:'long',year:'numeric',month:'long',day:'numeric'})}
setInterval(updateClock,1000);updateClock()
document.querySelectorAll('.tab-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')}))
function showSkeletons(id,c){const e=document.getElementById(id);e.innerHTML='';for(let i=0;i<c;i++){const d=document.createElement('div');d.className='skeleton skeleton-card';e.appendChild(d)}}
const goldData=[{name:'طلای ۱۸ عیار (هر گرم)',icon:'🥇',price:4850000,change:1.2},{name:'طلای ۲۴ عیار (هر گرم)',icon:'🥇',price:6460000,change:1.1},{name:'سکه امامی (طلا)',icon:'🪙',price:48200000,change:0.8},{name:'سکه بهار آزادی',icon:'🪙',price:32500000,change:-0.5},{name:'نیم سکه',icon:'🪙',price:24100000,change:0.6},{name:'ربع سکه',icon:'🪙',price:14200000,change:-0.3},{name:'طلای آب شده',icon:'💧',price:4870000,change:1.3},{name:'مظنه طلا',icon:'⚖️',price:4720000,change:0.9}]
function renderGold(){const c=document.getElementById('goldCards');c.innerHTML='';goldData.forEach(i=>{const ch=formatChange(i.change);const d=document.createElement('div');d.className='price-card gold-card';d.innerHTML='<div class="card-top"><span class="card-icon">'+i.icon+'</span><span class="card-change '+ch.cls+'">'+ch.arrow+' '+ch.text+'</span></div><div class="card-name">'+escapeHtml(i.name)+'</div><div class="card-price">'+formatNumber(i.price)+' <span class="card-unit">تومان</span></div>';c.appendChild(d)});document.getElementById('goldUpdate').textContent='به‌روزرسانی: '+new Date().toLocaleTimeString('fa-IR')}
const currencyData=[{name:'دلار آمریکا',icon:'🇺🇸',price:68500,change:0.5},{name:'یورو',icon:'🇪🇺',price:74200,change:0.8},{name:'پوند انگلیس',icon:'🇬🇧',price:87100,change:-0.2},{name:'درهم امارات',icon:'🇦🇪',price:18650,change:0.3},{name:'لیر ترکیه',icon:'🇹🇷',price:2010,change:-1.1},{name:'ین ژاپن',icon:'🇯🇵',price:460,change:0.1},{name:'یوآن چین',icon:'🇨🇳',price:9450,change:0.4},{name:'روبل روسیه',icon:'🇷🇺',price:740,change:-0.6},{name:'دلار کانادا',icon:'🇨🇦',price:50300,change:0.2},{name:'دلار استرالیا',icon:'🇦🇺',price:45800,change:0.7}]
function renderCurrency(){const c=document.getElementById('currencyCards');c.innerHTML='';currencyData.forEach(i=>{const ch=formatChange(i.change);const d=document.createElement('div');d.className='price-card';d.innerHTML='<div class="card-top"><span class="card-icon">'+i.icon+'</span><span class="card-change '+ch.cls+'">'+ch.arrow+' '+ch.text+'</span></div><div class="card-name">'+escapeHtml(i.name)+'</div><div class="card-price">'+formatNumber(i.price)+' <span class="card-unit">تومان</span></div>';c.appendChild(d)});document.getElementById('currencyUpdate').textContent='به‌روزرسانی: '+new Date().toLocaleTimeString('fa-IR')}
let cryptoLoaded=false
async function renderCrypto(s){if(s===undefined)s=true;if(s||!cryptoLoaded)showSkeletons('cryptoCards',8);try{const r=await fetch(proxyUrl('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=12&page=1&sparkline=false&price_change_percentage=24h'));if(!r.ok)throw new Error('API error');const data=await r.json();const c=document.getElementById('cryptoCards');c.innerHTML='';data.forEach(coin=>{const ch=formatChange(coin.price_change_percentage_24h);const d=document.createElement('div');d.className='price-card';d.innerHTML='<div class="card-top"><span class="card-icon"><img src="'+coin.image+'" alt="'+escapeHtml(coin.name)+'" style="width:28px;height:28px;border-radius:50%;" loading="lazy"></span><span class="card-change '+ch.cls+'">'+ch.arrow+' '+ch.text+'</span></div><div class="card-name">'+escapeHtml(coin.name)+' ('+escapeHtml(coin.symbol.toUpperCase())+')</div><div class="card-price">'+formatUSD(coin.current_price)+'</div>';c.appendChild(d)});cryptoLoaded=true;document.getElementById('cryptoUpdate').textContent='به‌روزرسانی: '+new Date().toLocaleTimeString('fa-IR')}catch(e){const fb=[{name:'Bitcoin (BTC)',price:67000,change:2.1,icon:'₿'},{name:'Ethereum (ETH)',price:3500,change:1.5,icon:'Ξ'},{name:'BNB (BNB)',price:600,change:-0.8,icon:'🟡'},{name:'Solana (SOL)',price:150,change:3.2,icon:'◎'},{name:'XRP (XRP)',price:0.62,change:-1.1,icon:'✕'},{name:'Cardano (ADA)',price:0.45,change:0.9,icon:'₳'},{name:'Dogecoin (DOGE)',price:0.12,change:-0.5,icon:'Ð'},{name:'Tether (USDT)',price:1.0,change:0.01,icon:'₮'}];const c=document.getElementById('cryptoCards');c.innerHTML='';fb.forEach(coin=>{const ch=formatChange(coin.change);const d=document.createElement('div');d.className='price-card';d.innerHTML='<div class="card-top"><span class="card-icon" style="font-size:1.4rem;">'+coin.icon+'</span><span class="card-change '+ch.cls+'">'+ch.arrow+' '+ch.text+'</span></div><div class="card-name">'+escapeHtml(coin.name)+'</div><div class="card-price">'+formatUSD(coin.price)+'</div>';c.appendChild(d)});document.getElementById('cryptoUpdate').textContent='داده آفلاین'}}
async function renderNews(){const c=document.getElementById('newsCards');c.innerHTML='';for(let i=0;i<6;i++){const d=document.createElement('div');d.className='skeleton skeleton-card';d.style.height='300px';c.appendChild(d)}try{const r=await fetch(proxyUrl('https://hacker-news.firebaseio.com/v0/topstories.json'));if(!r.ok)throw new Error('API error');const ids=await r.json();const top=ids.slice(0,12);const stories=await Promise.all(top.map(id=>fetch(proxyUrl('https://hacker-news.firebaseio.com/v0/item/'+id+'.json')).then(r=>r.json())));c.innerHTML='';const em=['💻','📱','🚀','🤖','🌐','⚡','🔧','🎮','☁️','🔐','📊','🛰️'];stories.forEach((s,idx)=>{if(!s||!s.title)return;const d=document.createElement('div');d.className='news-card';const u=s.url||('https://news.ycombinator.com/item?id='+s.id);let dom='news.ycombinator.com';try{dom=s.url?new URL(s.url).hostname.replace('www.',''):'news.ycombinator.com'}catch(e){}d.innerHTML='<div class="news-image">'+em[idx%em.length]+'</div><div class="news-body"><div class="news-source">'+escapeHtml(dom)+' — '+s.score+' امتیاز</div><div class="news-title">'+escapeHtml(s.title)+'</div><div class="news-desc">'+(s.descendants||0)+' نظر • '+toFaDigits(s.score)+' امتیاز</div><a class="news-link" href="'+escapeHtml(u)+'" target="_blank" rel="noopener noreferrer">خواندن خبر ←</a></div>';c.appendChild(d)});document.getElementById('newsUpdate').textContent='به‌روزرسانی: '+new Date().toLocaleTimeString('fa-IR')}catch(e){c.innerHTML='<p class="data-note">دریافت اخبار در حال حاضر ممکن نیست.</p>';document.getElementById('newsUpdate').textContent='خطا در دریافت'}}
document.getElementById('refreshGold').addEventListener('click',renderGold)
document.getElementById('refreshCurrency').addEventListener('click',renderCurrency)
document.getElementById('refreshCrypto').addEventListener('click',()=>renderCrypto(true))
document.getElementById('refreshNews').addEventListener('click',renderNews)
renderGold();renderCurrency();renderCrypto();renderNews()
setInterval(()=>renderCrypto(false),120000)
setInterval(renderNews,300000)
